<a href="https://colab.research.google.com/github/carolineli-maker/Python-Final-Project/blob/main/%E2%80%9C%E2%80%9CPython_Final_Project_ipynb%E2%80%9D%E7%9A%84%E5%89%AF%E6%9C%AC_ipynb%E2%80%9D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Green is the New Black: A Cross-national Analysis of Green Energy Transition

**Abstract**

This study explores the cross-national dynamics of renewable energy transitions using the Global Sustainable Energy Dataset from Our World in Data, within the period of 2000-2020. By analyzing country-level indicators such as renewable electricity generation, renewable energy share, and their correlation with factors like year and GDP growth, this project investigates how nations differ in their paths toward greener energy systems and how countries could learn from each other’s green transition paths. Four representative economies are selected, Germany, China, Brazil, and Ethiopia, to reflect a mix of developed, emerging, and developing contexts.

It seems that “going green” has become a global consensus nowadays. Over the past two decades, numerous governments have made up their mind to achieve net zero emissions, various multilateral collaborations were established to achieve the same goal, and even individuals have become increasingly aware of their environmental footprints. Yet behind this notion, a critical question lies: are all the countries going green at the same pace, and if not, what could we learn from each other’s different experiences and paths? This research aims to unravel the different paths adopted by each country in their universal goal of achieving an environmentally friendly society, and understand what structural and policy lessons could be learned from the differences in national experiences.

To answer these questions, the research looks at the Global Sustainable Energy Dataset to see who is “greener’’ and takes a step further to see how and why these differences emerged over time based on the different power structures of different countries.

In [ ]:
#import dataset
#Global Sustainable Energy Dataset from Our World in Data
#country-level annual indicators from 2000 to 2020
#renewable energy share in total final energy consumption
csv_url = "/content/global-data-on-sustainable-energy (1)_副本.csv"
csv_url

'/content/global-data-on-sustainable-energy (1)_副本.csv'

In [ ]:

import pandas as pd

In [ ]:
#convert the data to a dataframe
energydata = pd.read_csv(csv_url)
#have an overlook of the data
energydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   object
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   float64
 19  Latitude                                                          3648 non-null   float64
 20  Longitude                                                         3648 non-null   float64
dtypes: float64(18), int64(1), object(2)
memory usage: 598.8+ KB

In [ ]:
#pull 5 random samples
energydata.sample(5)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
1638,Israel,2020,100.000000,100.0,NaN,NaN,NaN,67.75,0.0,3.86,...,32593.8090,NaN,NaN,4.053859,-2.153428,44168.943640,400,20770.0,31.046051,34.851612
569,Cambodia,2002,18.187100,4.7,0.97,NaN,80.97,0.66,0.0,0.03,...,754.1447,7.05,2210.000038,NaN,6.578940,338.987477,95,181035.0,12.565679,104.990963
981,Dominican Republic,2015,98.560360,89.0,72.48,70000.0,14.88,15.59,0.0,1.32,...,9354.6420,2.21,23590.000150,NaN,6.927019,6921.520594,225,48670.0,18.735693,-70.162651
561,Burundi,2015,8.427652,0.2,5.69,2490000.0,91.15,0.03,0.0,0.15,...,193.7544,7.38,400.000006,NaN,-3.900003,305.549652,463,27830.0,-3.373056,29.918886
28,Albania,2007,100.000000,58.1,NaN,NaN,NaN,0.07,0.0,2.76,...,9534.8740,3.12,4139.999866,NaN,5.983260,3595.038057,105,28748.0,41.153332,20.168331

In [ ]:
#see the columns in the dataset
energydata.columns.tolist()

['Entity',
 'Year',
 'Access to electricity (% of population)',
 'Access to clean fuels for cooking',
 'Renewable-electricity-generating-capacity-per-capita',
 'Financial flows to developing countries (US $)',
 'Renewable energy share in the total final energy consumption (%)',
 'Electricity from fossil fuels (TWh)',
 'Electricity from nuclear (TWh)',
 'Electricity from renewables (TWh)',
 'Low-carbon electricity (% electricity)',
 'Primary energy consumption per capita (kWh/person)',
 'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
 'Value_co2_emissions_kt_by_country',
 'Renewables (% equivalent primary energy)',
 'gdp_growth',
 'gdp_per_capita',
 'Density\\n(P/Km2)',
 'Land Area(Km2)',
 'Latitude',
 'Longitude']

In [ ]:
#covert year to datetime to make pandas realize the column Year is a time
energydata['Year_dt'] = pd.to_datetime(energydata['Year'], format='%Y')

In [ ]:
#basic cleaning
#check data types
energydata.dtypes

Entity                                                                      object
Year                                                                         int64
Access to electricity (% of population)                                    float64
Access to clean fuels for cooking                                          float64
Renewable-electricity-generating-capacity-per-capita                       float64
Financial flows to developing countries (US $)                             float64
Renewable energy share in the total final energy consumption (%)           float64
Electricity from fossil fuels (TWh)                                        float64
Electricity from nuclear (TWh)                                             float64
Electricity from renewables (TWh)                                          float64
Low-carbon electricity (% electricity)                                     float64
Primary energy consumption per capita (kWh/person)                         float64
Energy intensity level of primary energy (MJ/$2017 PPP GDP)                float64
Value_co2_emissions_kt_by_country                                          float64
Renewables (% equivalent primary energy)                                   float64
gdp_growth                                                                 float64
gdp_per_capita                                                             float64
Density\n(P/Km2)                                                            object
Land Area(Km2)                                                             float64
Latitude                                                                   float64
Longitude                                                                  float64
Year_dt                                                             datetime64[ns]
dtype: object

In [ ]:
#find duplicated rows
energydata[energydata.duplicated(keep=False)].head(10)

Empty DataFrame
Columns: [Entity, Year, Access to electricity (% of population), Access to clean fuels for cooking, Renewable-electricity-generating-capacity-per-capita, Financial flows to developing countries (US $), Renewable energy share in the total final energy consumption (%), Electricity from fossil fuels (TWh), Electricity from nuclear (TWh), Electricity from renewables (TWh), Low-carbon electricity (% electricity), Primary energy consumption per capita (kWh/person), Energy intensity level of primary energy (MJ/$2017 PPP GDP), Value_co2_emissions_kt_by_country, Renewables (% equivalent primary energy), gdp_growth, gdp_per_capita, Density\n(P/Km2), Land Area(Km2), Latitude, Longitude, Year_dt]
Index: []

[0 rows x 22 columns]

In [ ]:
#drop duplicated rows
energydata = energydata.drop_duplicates(keep='first')

In [ ]:
#check datashape
energydata.shape

(3649, 22)

In [ ]:

#check the cleaned data
energydata.head()

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude,Year_dt
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953,2000-01-01
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953,2001-01-01
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953,2002-01-01
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953,2003-01-01
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953,2004-01-01

In [ ]:
#check the columns' names again
energydata.columns.tolist()

['Entity',
 'Year',
 'Access to electricity (% of population)',
 'Access to clean fuels for cooking',
 'Renewable-electricity-generating-capacity-per-capita',
 'Financial flows to developing countries (US $)',
 'Renewable energy share in the total final energy consumption (%)',
 'Electricity from fossil fuels (TWh)',
 'Electricity from nuclear (TWh)',
 'Electricity from renewables (TWh)',
 'Low-carbon electricity (% electricity)',
 'Primary energy consumption per capita (kWh/person)',
 'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
 'Value_co2_emissions_kt_by_country',
 'Renewables (% equivalent primary energy)',
 'gdp_growth',
 'gdp_per_capita',
 'Density\\n(P/Km2)',
 'Land Area(Km2)',
 'Latitude',
 'Longitude',
 'Year_dt']

The first step ranks the countries by the amount of electricity generated from renewables and calculates the renewable energy share, to see the proportion of renewable energy in the final energy consumption. The result has shown that despite the large amount of electricity generated by countries like China and the U.S., countries with the largest energy share are located primarily in Africa, such as Ethiopia and Zambia. However, the high rank does not translate to a leading position in energy transition. Their high shares are due to the overall lower power consumption and the over-reliance on the traditional biomass sources, such as firewood and crops. By contrast, some middle to high-income countries have a relatively low share of renewable energy but have achieved an energy transition in the past 20 years.

To further illustrate these global disparities and provide a more detailed understanding of how different countries progress along the path of energy transition, I selected four representative economies: China, Germany, Brazil, and Ethiopia, to analyze how their renewable energy share has evolved over the past two decades. Each of the countries selected has its unique path and characteristics. China is currently undergoing rapid energy transitions, especially in the field of electric vehicles. Germany represents a highly industrialized, policy-driven economy, while Brazil is a middle-income country with a historically high but hydro-dependent renewable share. Lastly, Ethiopia, which ranked high on the renewable energy share chart, is a low-income country with limited but growing capacity.

In [ ]:
#I want to see which country is using the most renewable electricity
#group the data by country
by_country = energydata.groupby('Entity')
#sum the electricity used from the renewables
renewable_sum = by_country['Electricity from renewables (TWh)'].sum()
#sort by descending order
renewable_sum_sorted = renewable_sum.sort_values(ascending=False)

In [ ]:
#show the first 20 rows
renewable_top20 = renewable_sum_sorted.head(20)
renewable_top20

Entity
China             19702.94
United States     10234.10
Brazil             8511.46
Canada             8167.16
India              3463.36
Norway             2775.43
Japan              2723.67
Germany            2633.80
Sweden             1777.30
France             1708.15
Italy              1681.25
Spain              1614.05
Turkey             1284.98
Paraguay           1131.52
Mexico             1011.55
United Kingdom     1004.27
Austria             966.63
Colombia            947.07
Switzerland         713.67
Argentina           710.04
Name: Electricity from renewables (TWh), dtype: float64

In [ ]:
#import plotly
import plotly.express as px

In [ ]:

#Which country is greener?

renewable_share = (energydata.groupby('Entity')['Renewable energy share in the total final energy consumption (%)']
                   .mean().sort_values(ascending=False).head(15).reset_index())

fig = px.bar(
    renewable_share,
    x='Entity',
    y='Renewable energy share in the total final energy consumption (%)',
    title='Average Renewable Energy Share by Country (Top 15)',
    labels={'Entity': 'Country', 'Renewable energy share in the total final energy consumption (%)': 'Renewable Energy Share (%)'}
)
fig.show()

The second step of the research involves conducting a time-series analysis to visualize their trajectory in using renewable energy. Germany has experienced a steady upward trend, increasing from nearly zero in 2000 to 20% in 2020. Interestingly, China’s renewable energy share in total final energy consumption shows a declining trend between 2000 and 2020. This might be counterintuitive at first glimpse; however, this is likely due to the rapid expansion of the overall energy demand, especially in the 2000s. Therefore, while the renewable output is increasing in general, its share in final consumption shows a downward-sloping trend. Moreover, Brazil and Ethiopia maintain a consistent high share, due to the hydropower dominance in Brazil and the reliance on traditional biomass in Ethiopia.

In [ ]:

#select four representative countries from the data
focus = energydata [energydata['Entity'].isin(['Germany', 'China', 'Brazil', 'Ethiopia'])]

by_pair = focus.groupby(['Entity', 'Year'])[
    'Renewable energy share in the total final energy consumption (%)'
].mean().reset_index()

fig = px.scatter(
    by_pair,
    x='Year',
    y='Renewable energy share in the total final energy consumption (%)',
    color='Entity',
    facet_col='Entity',
    facet_col_wrap=2,
    title='Renewable Energy Share Trends (2000–2020): Germany, China, Brazil, Ethiopia',
    trendline='ols'
)
fig.show()

To further test the visual patterns observed in Step 2, Step 3 introduces a quantitative correlation analysis examining how renewable energy shares relate to time (Year) and to economic growth (GDP growth rate).

In [ ]:
#start correlation analysis
#The correlation between Year and Renewable Energy Share
#rename the column
col_share = 'Renewable energy share in the total final energy consumption (%)'

countries = ['Germany', 'China', 'Brazil', 'Ethiopia']

In [ ]:
#filter four countries and necessary columns and drop the null
filtered = energydata[energydata['Entity'].isin(countries)]
filtered = filtered[['Entity', 'Year', 'Renewable energy share in the total final energy consumption (%)']]
filtered = filtered.dropna()

In [ ]:
#calculate the correlations
correlations = {}
for country, group in filtered.groupby('Entity'):
    corr_value = group['Year'].corr(
        group['Renewable energy share in the total final energy consumption (%)'],
        method='pearson'
    )
    correlations[country] = corr_value

In [ ]:
#print the result
print("Pearson Correlation between Year and Renewable Energy Share for selected countries:")
for country, corr_value in correlations.items():
    print(f"{country}: {corr_value:.4f}")

Pearson Correlation between Year and Renewable Energy Share for selected countries:
Brazil: 0.2421
China: -0.8094
Ethiopia: -0.9178
Germany: 0.9855

The result revealed fundamental differences in the pace and nature of energy transitions across four cases. Germany shows a strong correlation close to 1, further indicating its renewable energy share is steadily increasing over the years, confirming that Germany’s long-term regulatory commitment has proven to be effective in lowering its carbon footprint. Brazil exhibits a moderate positive relationship. The limited change indicates a structural inertia: Brazil’s energy mix is already “green” in numerical terms, but lacks resilience to droughts.
By comparison, the correlation relations appear to be strongly negative in China and Ethiopia, revealing the conflict between rapid expansion and green transition. In the case of China, the green energy share is diluted by the large amount of power consumed, while Ethiopia’s decline is primarily due to traditional biomass dominance. Although hydropower expanded, the share of modern renewables remains marginal compared with traditional power.

In [ ]:
#The correlation between gdp_growth and Renewable Energy Share for selected countries
#filter the columns
filtered = energydata[energydata['Entity'].isin(countries)]
filtered = filtered[['Entity', 'gdp_growth', 'Renewable energy share in the total final energy consumption (%)']]
filtered = filtered.dropna()

#calculate the correlations
correlations = {}
for country, group in filtered.groupby('Entity'):
    corr_value = group['gdp_growth'].corr(
        group['Renewable energy share in the total final energy consumption (%)'],
        method='pearson'
    )
    correlations[country] = corr_value
#print the result
print("Pearson Correlation between gdp_growth and Renewable Energy Share for selected countries:")
for country, corr_value in correlations.items():
    print(f"{country}: {corr_value:.4f}")

Pearson Correlation between gdp_growth and Renewable Energy Share for selected countries:
Brazil: 0.1882
China: 0.1439
Ethiopia: -0.0614
Germany: 0.0900

When examining the correlation between GDP growth and renewable energy share, the four countries show weak correlations, suggesting that short-term economic growth exerts a negligible influence on renewable energy penetration. The major factor driving energy transition is the structural and political reform in the long run, rather than the spur of the economy. In other words, the economy might grow, but without proper technical investment and green policy in place, the energy mix will not automatically transition to low-carbon alongside the expansion of economies.

In Conclusion, the global green energy transition is neither synchronized with economic growth nor automatic. It relies on systemic policy-making and structural vision. The key to sustainable development depends less on how fast economies grow and more on how persistently governments and societies commit to long-term structural change. Green energy transition, therefore, is not simply about technology or time; it is about policy persistence, institutional design, and collective will.

Note: The majority of the Python code in this project is written based on the Professor’s lecture notes on Pandas. I also used the tutorial on GeekforGeeks to do the correlation analysis, along with the help of ChatGPT to explain the code and fix the errors. I have attached the links to GeekforGeeks and my conversation with ChatGPT below:
https://www.geeksforgeeks.org/pandas/python-pandas-dataframe-corr/
https://chatgpt.com/share/68fe3357-1b98-8003-93fd-37f17804eb71